name: Release 📦
on:
  workflow_dispatch:
  push:
    branches:    
      - main
      - 'releases/**'
      
jobs:
  release:
    name: release 📦
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Release
      uses: relekang/action-semantic-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
